### ISSUE TITLE
I need help building the project

### ISSUE THREAD

**Issue by aidybobs** [HearthSim/UnityHook#18]
I am using UnityHook for my a-level computer science project in which i will use this project to determine when you play a card in hearthstone, which card is played and on which side of the board then calculate real time statistics from the data but i cannot get unityhook to build at all can someone just walk me through the steps they took to make it work?

**Comment by aidybobs** [comment]
also i am fairly new to programming sorry about that :)

**Comment by jleclanche** [comment]
Turn on logging and use hslog to parse the logs into game state instead. 

https://github.com/jleclanche/fireplace/wiki/How-to-enable-logging

https://github.com/HearthSim/python-hslog

**Comment by aidybobs** [comment]
I am coding in c# will it work with the rest of my program?

**Comment by jleclanche** [comment]
I can't help beyond this, sorry. UnityHook is not what you want though, it's easier and more reliable to get the game state out of the log files.

**Comment by aidybobs** [comment]
okay thanks

**Comment by Bert-Proesmans** [comment]
I don't recommend using UnityHook, there are a lot of gotcha's to correctly hook into the mono runtime and there are no guarantees about how long your implementation would remain working. Picking a more stable interface, like the power log, is a better option.

Staying within the c# ecosystem is possible but a little tricky. HDT uses a handler from which you could get inspiration: 
https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/de55de164bb602bb84f46e847da76bb28adf76b5/Hearthstone%20Deck%20Tracker/LogReader/Handlers/PowerHandler.cs#L20
The way to tackle this is to have a file watcher attached to your game log file and have newly written lines processed by your handler to transform them into one of your own (domain) objects.

Using python-hslog is also possible, but the file watching code and line parsing happen within a python executable. Since your other logic is written in c#, you could combine both runtimes using PythonNet or IronPython.. but doing this is beyond me, integration doesn't work perfectly either.

The most robust solution would be to have your domain objects written down in Cap'n'Proto, Protobuf or JSON schema objects. Use python-hslog for log parsing, serialize and send the domain objects accross localhost to your c# program. Deserialize incoming domain objects into c# objects to work with them.
